### ISSUE TITLE
Feature request ? return only star list

### ISSUE THREAD

**Issue by gnthibault** [toros-astro/astroalign#37]
Thank you for this awesome project, astroalign definitely allows to make fast prototyping for deep sky image processing :)

I have plenty of project that were blocked due to the lack of existence of a tool like astroalign in python.

I am building some tools that are based on the star position, that I would like to use to infer centroid, and model the psf.
To do so, I am trying to do like in the following example:

`transf, (s_list, t_list) = aa.find_transform(source, target)
`
However, when only the star position is needed I guess there is a simple solution no ?

Thank you in advance for your help

**Comment by martinberoiz** [comment]
Hello, thank you for your kind words. 

If you only require the centroids and you're not interested in the transformation, the usual way to do it, is to either assign a dummy variable

    __, (s_list, t_list) = aa.find_transform(source, target)

Or select the second item right after you call like this

    s_list, t_list = aa.find_transform(source, target)[1]

You can also create a wrapper function that formats and returns the values you're interested in.

Would this solve your issue?

**Comment by gnthibault** [comment]
Thank you for your comment !
I know how to ignore the return values I don't need. I did not checked what you used for detection stars, but here is what I had in mind:

-Either is is possible to call directly the method that detects the stars, because I don't need the asterism matching part. That would save some time and make the code a bit nicer.

-The best for me would be, in addition to get the detectected centroid coordinates, a set of parameter estimate for the psf / gaussian profile or whatever is used.

Thank you very much for your support, I'd be already happy if you could point me out to the point in the code where you do the star detection.

**Comment by martinberoiz** [comment]
Oh, I'm sorry I misunderstood your question. For source detection I basically use sep. I would recommend using [`sep`](https://github.com/kbarbary/sep) or [`photutils`](https://photutils.readthedocs.io/en/stable/) instead, because my wrapper is pretty simple and naive, but you can still check the code I use, it's in the private [`_find_sources`](https://github.com/toros-astro/astroalign/blob/69e3dec08670d7b6bd3b4235acc036c10a903cf6/astroalign.py#L383) method.

SEP does not estimate psf AFAIK, but if you're looking for something like that, you may want to open an issue in [properimage](https://github.com/toros-astro/ProperImage). The author there does PSF estimation, I can't remember now what method he uses.

**Comment by gnthibault** [comment]
Thank you very much for all those references !

**Comment by martinberoiz** [comment]
you're welcome, I'm glad I could help.
