### ISSUE TITLE
find_transform is not deterministic

### ISSUE THREAD

**Issue by davidenitti** [toros-astro/astroalign#49]
if I apply the same find_transform function multiple times I don't get the same transformation.

**Comment by martinberoiz** [comment]
Hi, yes, this could be possible. But the transformations should be very very similar, are you getting wildly different results?

The core of this issue is that we use RANSAC (Random Sampling Consensus) to find the best transformation, which is by random in nature. I recently came to know there is a deterministic RANSAC (see #47) that would give repeatable results. But it would take me a while to implement tbh.

**Comment by davidenitti** [comment]
thanks, I understand now,
I was just wondering why there was this stochastic behavior, thanks for the reply.

**Comment by martinberoiz** [comment]
Hi, I know this is a closed issue, but you should check version 2.4 now that implements a deterministic approach to asterism matching.
